### ISSUE TITLE
Purge on version change

### ISSUE THREAD

**Issue by jayvdb** [morlandi/django-tables-cleaner#6]
See https://github.com/QueraTeam/django-qsessions/issues/12 .  I am often switching between django versions on the same database, and it would be nice to trigger a purge of all records on a table when switching.

This is also related to / builds on top of https://github.com/morlandi/django-tables-cleaner/issues/5 , which would run schedules on non-periodic events like startup.

To do this, we would need some data storage that records the current django version in the db, so it can be compared against when starting up again, and trigger event when changed.  This is likely best done in an external app.  I am going to cross-link this with an issue in https://github.com/raratiru/django-quenv , another app I am using and has a motivated maintainer who is thinking about these types of things.

**Comment by morlandi** [comment]
I guess "table cleaning" is just one of many actions you need when switching Django version.

A separate app would be more appropriate, and a simple script will be often sufficient
